[package]
name = "linter_test"
version = "0.1.0"
edition = "2021"

[dependencies]
gazebo.version = "0.8.0"
gazebo.path = "../../gazebo/gazebo" # @oss-disable
gazebo_lint = { path = "../gazebo_lint" }
anyhow = "1.0.65"
