[package]
edition = "2021"
name = "linter_test"
version = "0.1.0"

[dependencies]
anyhow = "1.0.65"
gazebo.path = "../../gazebo/gazebo" # @oss-disable
gazebo.version = "0.8.1"
gazebo_lint = { path = "../gazebo_lint" }
