[package]
name = "gazebo_lint"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
authors = ["Facebook"]
description = "A linter for the Gazebo Rust library"
repository = "https://github.com/facebookincubator/gazebo_lint"

[lib]
plugin = true

[dependencies]
smallvec = "1.4"
